resolver: lts-18.28

packages:
- .

nix:
  packages:
    - zlib
    - xorg.libX11
    - xorg.libXrandr
    - xorg.libXScrnSaver
    - xorg.libXext
    - pkg-config
    - xorg.libXft
    - xorg.libXrender
